apiVersion: apps/v1
kind: Deployment

metadata:
  name: mymongo-dev-deployment
  labels:
    app: mymongo
    type: db

spec:
  template:
    metadata:
      name: mymongo-dev-pod
      labels:
        app: mymongo
        type: db
    spec:
      containers:
        - name: mymongo-container
          image: mongo
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
              subPath: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mymongo-dev-config
                  key: MONGO_INITDB_DATABASE
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mymongo-dev-pvc

  selector:
    matchLabels:
      app: mymongo
      type: db
