apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv-dev-local
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./"